import {applyTerrainBrush,type TerrainBrush} from './terrain-brush';
import {createTerrainGrid,TERRAIN_PAINTS} from '../../shared/terrain-grid';
import '@fontsource/barlow-condensed/600.css';
import '@fontsource/ibm-plex-mono/400.css';
import '@fontsource/ibm-plex-sans/400.css';
import './style.css';
import {EditorScene} from './scene';
import {EditorHistory} from './history';
import {newMapDocument,validateMapDocument,mapWarnings,BUILDING_TEMPLATES,type MapDocument,type EditorObject,type BuildingTemplate} from '../../shared/map-editor';
import {terrainHeight} from '../../shared/terrain';
import {getMap} from '../../shared/maps';
import {icon} from '../ui/icons';
const app=document.querySelector<HTMLElement>('#editor-app')!;
const esc=(s:unknown)=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const uid=()=>crypto.randomUUID().slice(0,12),history=new EditorHistory();
type Saved={draft:MapDocument;published:MapDocument|null;updatedAt:string};
let brush:TerrainBrush={mode:'raise',radius:24,strength:6,height:0,paint:'grass'};
let doc=newMapDocument(),records:Saved[]=[],scene:EditorScene,selected:string|null=null,pending:EditorObject|null=null,tab='objects',dirty=false,busy=false;
async function api(path:string,body?:unknown){const response=await fetch(path,{method:body?'POST':'GET',credentials:'same-origin',headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined,signal:AbortSignal.timeout(15000)});if(!response.headers.get('content-type')?.includes('application/json'))throw Error('A API do editor está indisponível. Reinicie o servidor do jogo e tente novamente.');const data=await response.json();if(!response.ok)throw Error(data.error||'Servidor indisponível.');return data;}
const el=(id:string)=>document.getElementById(id)!;
const input=(id:string)=>el(id) as HTMLInputElement;
function status(message:string,error=false){el('editor-message').textContent=message;el('editor-message').classList.toggle('error',error);}
function persistLocal(){try{localStorage.setItem('warcats-editor-recovery',JSON.stringify(doc));localStorage.setItem('warcats-editor-last',doc.id);}catch{status('Sem espaço no navegador. Salve o rascunho no servidor.',true);}}
function mark(){dirty=true;el('save-state').textContent='ALTERAÇÕES NÃO SALVAS';persistLocal();}
function commit(change:()=>void){if(busy)return;const previous=structuredClone(doc);try{change();validateMapDocument(doc);history.push(previous);mark();draw();}catch(e){doc=previous;draw();status((e as Error).message,true);}}
function draw(){scene.renderMap(doc);scene.select(selected);el('map-title').textContent=doc.name;el('map-size').textContent=`${doc.limit*2} × ${doc.limit*2} M`;el('object-count').textContent=`${doc.objects.length} OBJETOS · ${doc.hills.length} ELEVAÇÕES`;(el('undo') as HTMLButtonElement).disabled=!history.canUndo;(el('redo') as HTMLButtonElement).disabled=!history.canRedo;inspector();if(pending)scene.setGhost(pending,doc);}
function choose(id:string|null){scene.setBrush(0);pending=null;scene.setGhost(null,doc);selected=id;scene.select(id);inspector();el('placement-help').textContent='SELECIONAR · G MOVER · R GIRAR · F CENTRALIZAR · DELETE REMOVER';}
function tool(object:EditorObject){scene.setBrush(0);selected=null;pending=object;scene.setGhost(object,doc);inspector();el('placement-help').textContent=`${object.name.toUpperCase()} · CLIQUE COLOCA · R GIRA · ESC SAI DA COLOCAÇÃO`;}
const baseObject=(kind:EditorObject['kind'],name:string):EditorObject=>({id:uid(),kind,name,x:0,y:0,z:0,yaw:0,w:3.2,h:1.1,d:.8,material:'concrete'});
function library(){
 el('palette-tabs').querySelectorAll('button').forEach(b=>{b.classList.toggle('active',b.dataset.tab===tab);b.setAttribute('aria-selected',String(b.dataset.tab===tab));});
 const root=el('palette');
 if(tab==='objects'){
  root.innerHTML=`<p class="panel-intro">Escolha uma peça e clique no terreno. O contorno mostra onde ela será colocada.</p><h3>ESTRUTURAS TÁTICAS</h3><div class="asset-grid">${doc.templates.map(t=>`<button data-template="${t.id}">${icon('building')}<b>${esc(t.name)}</b><small>${t.width} × ${t.depth} M · ${t.floors} PAV.</small></button>`).join('')}</div><h3>COBERTURA E LOGÍSTICA</h3><div class="asset-grid">${[['wall','Parede de concreto'],['container','Contêiner'],['road','Trecho de asfalto'],['helipad','Heliponto'],['truck','Caminhão militar'],['crate','Caixa de suprimentos'],['fuel','Tambor de combustível'],['generator','Gerador'],['radar','Radar de campanha']].map(([id,name])=>`<button data-asset="${id}">${icon(id==='wall'?'build':'supply')}<b>${name}</b><small>${['wall','container','road','helipad'].includes(id)?'PEÇA MODULAR':'ASSET 3D'}</small></button>`).join('')}</div>`;
  root.querySelectorAll<HTMLElement>('[data-template]').forEach(b=>b.onclick=()=>{const t=doc.templates.find(t=>t.id===b.dataset.template)!;tool({...baseObject('building',t.name),template:t.id,w:t.width,d:t.depth,h:t.floors*t.floorHeight});});
  root.querySelectorAll<HTMLElement>('[data-asset]').forEach(b=>b.onclick=()=>{const id=b.dataset.asset!;const object=baseObject('box',b.querySelector('b')!.textContent!);if(id==='container')Object.assign(object,{w:12,d:2.5,h:2.8,material:'rust'});else if(id==='road')Object.assign(object,{kind:'road',w:24,d:12,h:.05,material:'dark'});else if(id==='helipad')Object.assign(object,{kind:'helipad',w:20,d:20,h:.05});else if(id!=='wall')Object.assign(object,{kind:'prop',asset:id});tool(object);});
 } else if(tab==='buildings'){
  root.innerHTML=`<p class="panel-intro">Crie um prédio reutilizável com portas, janelas, lajes e escada até a cobertura.</p><form id="building-form"><label>MODELO EXISTENTE<select id="template-edit"><option value="">CRIAR NOVO</option>${doc.templates.map(t=>`<option value="${t.id}">${esc(t.name)}</option>`).join('')}</select></label><label>NOME<input id="template-name" value="Posto avançado" maxlength="60" required minlength="2"/></label><div class="form-grid"><label>LARGURA · M<input id="template-width" type="number" value="16" min="8" max="40"/></label><label>PROFUNDIDADE · M<input id="template-depth" type="number" value="18" min="10" max="45"/></label><label>PAVIMENTOS<input id="template-floors" type="number" value="2" min="1" max="4"/></label><label>PÉ-DIREITO · M<input id="template-floorHeight" type="number" value="3.2" min="2.8" max="6" step=".1"/></label><label>PORTA · M<input id="template-doorWidth" type="number" value="3.6" min="2.4" max="10" step=".2"/></label><label>ACABAMENTO<select id="template-facade"><option value="brick">Tijolo militar</option><option value="plaster">Concreto</option><option value="steel">Chapa de aço</option></select></label></div><button class="primary" type="submit">SALVAR PRÉDIO NA BIBLIOTECA ${icon('check')}</button></form><p class="panel-note">O prédio fica salvo com o mapa. Novos mapas herdam sua biblioteca atual. Você também pode importar modelos dos mapas salvos.</p>`;
  el('template-edit').onchange=()=>{const t=doc.templates.find(t=>t.id===input('template-edit').value);if(t)for(const key of ['name','width','depth','floors','floorHeight','doorWidth','facade'] as const)input('template-'+key).value=String(t[key]);};
  el('building-form').onsubmit=e=>{e.preventDefault();const t:BuildingTemplate={id:input('template-edit').value||uid(),name:input('template-name').value.trim(),width:+input('template-width').value,depth:+input('template-depth').value,floors:+input('template-floors').value,floorHeight:+input('template-floorHeight').value,doorWidth:+input('template-doorWidth').value,facade:input('template-facade').value as BuildingTemplate['facade']};try{const next={...doc,templates:[...doc.templates.filter(v=>v.id!==t.id),t]};validateMapDocument(next);commit(()=>doc=next);tab='objects';library();tool({...baseObject('building',t.name),template:t.id,w:t.width,d:t.depth,h:t.floors*t.floorHeight});status('Prédio criado. Clique no mapa para colocar.');}catch(e){status((e as Error).message,true);}};
 } else if(tab==='terrain'){
  root.innerHTML=`<p class="panel-intro">Pinte e modele diretamente no mapa. Segure o botão esquerdo e arraste. Cada traço pode ser desfeito.</p><div class="brush-modes">${[['raise','ELEVAR'],['lower','REBAIXAR'],['flatten','NIVELAR'],['smooth','SUAVIZAR'],['paint','PINTAR']].map(([id,name])=>`<button data-brush="${id}" class="${brush.mode===id&&scene.brushRadius?'active':''}">${name}</button>`).join('')}</div><label>RAIO DO PINCEL · M<input id="brush-radius" type="range" min="6" max="100" value="${brush.radius}"/><output id="radius-value">${brush.radius} M</output></label><label>INTENSIDADE<input id="brush-strength" type="range" min="1" max="20" value="${brush.strength}"/></label><label>ALTURA PARA NIVELAR · M<input id="brush-height" type="number" min="-12" max="70" step=".5" value="${brush.height}"/></label><div class="paint-swatches">${Object.entries(TERRAIN_PAINTS).map(([id,p])=>`<button data-paint="${id}" class="${brush.paint===id?'active':''}"><i style="background:#${p.color.toString(16)}"></i>${p.name}</button>`).join('')}</div><button id="stop-brush" class="secondary">ENCERRAR PINCEL · ESC</button><h3>MONTANHA PARAMÉTRICA</h3><label>ALTURA · M<input id="hill-height" type="number" value="12" min="-12" max="60" step="1"/></label><label>RAIO · M<input id="hill-radius" type="number" value="48" min="12" max="240" step="2"/></label><button id="add-hill" class="primary">ADICIONAR NO CENTRO DA VISTA</button><div class="entity-list">${doc.hills.map(h=>`<button data-hill="${h.id}">${icon('map')} ELEVAÇÃO ${Math.round(h.height)} M <small>RAIO ${h.radius} M</small></button>`).join('')}</div>`;
  const activateBrush=()=>{choose(null);scene.setBrush(brush.radius);el('placement-help').textContent='PINCEL DE TERRENO · SEGURE E ARRASTE · CTRL Z DESFAZ O TRAÇO · ESC SAI';library();};
  root.querySelectorAll<HTMLElement>('[data-brush]').forEach(b=>b.onclick=()=>{brush.mode=b.dataset.brush as TerrainBrush['mode'];activateBrush();});
  root.querySelectorAll<HTMLElement>('[data-paint]').forEach(b=>b.onclick=()=>{brush.paint=b.dataset.paint as TerrainBrush['paint'];brush.mode='paint';activateBrush();});
  input('brush-radius').oninput=()=>{brush.radius=+input('brush-radius').value;el('radius-value').textContent=brush.radius+' M';if(scene.brushRadius)scene.setBrush(brush.radius);};
  input('brush-strength').oninput=()=>brush.strength=+input('brush-strength').value;
  input('brush-height').onchange=()=>brush.height=Math.max(-12,Math.min(70,+input('brush-height').value||0));
  el('stop-brush').onclick=()=>{choose(null);library();};
  el('add-hill').onclick=()=>{const radius=+input('hill-radius').value,height=+input('hill-height').value;if(!Number.isFinite(radius)||radius<12||radius>240||!Number.isFinite(height)||height< -12||height>60)return status('Informe altura e raio dentro dos limites.',true);const id=uid();commit(()=>doc.hills.push({id,x:Math.round(scene.orbit.target.x),z:Math.round(scene.orbit.target.z),height,radius}));selected='hill:'+id;scene.select(selected);inspector();library();};
  root.querySelectorAll<HTMLElement>('[data-hill]').forEach(b=>b.onclick=()=>{choose('hill:'+b.dataset.hill);scene.focus(selected);});
 } else {
  root.innerHTML=`<p class="panel-intro">Comece do zero ou edite uma operação existente. Salvar mantém o rascunho privado.</p><label>CENÁRIO INICIAL<select id="new-base"><option value="">Terreno vazio</option><option value="nordhaven">Nordhaven</option><option value="quarry">Pedreira Kestrel</option><option value="harbor">Porto Blackwater</option></select></label><button id="new-map" class="primary">CRIAR MAPA</button><button id="recover" class="secondary">RECUPERAR CÓPIA DESTE NAVEGADOR</button><button id="import-templates" class="secondary">IMPORTAR PRÉDIOS DOS MAPAS SALVOS</button><h3>MAPAS SALVOS</h3><div class="saved-list">${records.map(r=>`<button data-open="${r.draft.id}"><b>${esc(r.draft.name)}</b><small>R${r.draft.revision} · ${r.published?'DISPONÍVEL PARA JOGAR':'RASCUNHO'}</small></button>`).join('')||'<p>Nenhum rascunho salvo ainda.</p>'}</div><button id="export" class="secondary">EXPORTAR MAPA JSON</button><label class="secondary file-button">IMPORTAR MAPA<input id="import" type="file" accept="application/json,.json"/></label>`;
  el('new-map').onclick=()=>{const base=input('new-base').value as MapDocument['base'];const templates=doc.templates;choose(null);commit(()=>{doc=newMapDocument(base||null);doc.templates=structuredClone(templates);});selected=null;scene.focus();library();status('Novo mapa criado. Ajuste as bases e o objetivo no painel direito.');};
  root.querySelectorAll<HTMLElement>('[data-open]').forEach(b=>b.onclick=()=>{const r=records.find(r=>r.draft.id===b.dataset.open)!;choose(null);persistLocal();doc=structuredClone(r.draft);history.clear();dirty=false;selected=null;draw();library();el('save-state').textContent=`RASCUNHO R${doc.revision}`;});
  el('import-templates').onclick=()=>{commit(()=>{for(const r of records)for(const t of r.draft.templates)if(!doc.templates.some(v=>v.id===t.id)&&doc.templates.length<50)doc.templates.push(structuredClone(t));});status('Prédios dos mapas salvos adicionados à biblioteca deste mapa.');};
  el('recover').onclick=()=>{try{const recovered=validateMapDocument(JSON.parse(localStorage.getItem('warcats-editor-recovery')||'null'));commit(()=>doc=recovered);library();status('Cópia local recuperada.');}catch{status('Nenhuma cópia local válida encontrada.',true);}};
  el('export').onclick=()=>{const blob=new Blob([JSON.stringify(doc,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=doc.id+'.json';a.click();URL.revokeObjectURL(url);};
  input('import').onchange=async()=>{try{const file=input('import').files?.[0];if(!file)return;if(file.size>524288)throw Error('Arquivo excede 512 KB.');const imported=validateMapDocument(JSON.parse(await file.text()));commit(()=>doc={...imported,id:'map-'+uid(),revision:0});selected=null;draw();library();status('Mapa importado como novo rascunho.');}catch(e){status((e as Error).message,true);}};
 }
}
function inspector(){
 const root=el('inspector'),o=doc.objects.find(o=>o.id===selected),hill=doc.hills.find(h=>'hill:'+h.id===selected),spawn=selected?.startsWith('spawn-')?Number(selected.slice(6)):-1,zone=selected==='zone';
 if(pending){root.innerHTML=`<h2>COLOCAR OBJETO</h2><p>${esc(pending.name)}</p><p class="panel-intro">Mova o cursor no cenário. Clique para colocar quantas cópias precisar.</p><button id="cancel-place" class="secondary">ENCERRAR COLOCAÇÃO · ESC</button>`;el('cancel-place').onclick=()=>choose(null);return;}
 if(o||hill||spawn>=0||zone){
  const p=o??hill??(zone?doc.zone:doc.spawns[spawn]);const title=o?.name??(hill?'Elevação':zone?'Objetivo A':`Base ${['LYNX','EMBER','GHOST'][spawn]}`);
  root.innerHTML=`<span class="eyebrow">ELEMENTO SELECIONADO</span><h2>${esc(title)}</h2><form id="properties"><div class="form-grid">${['x',...(o?['y']:[]),'z'].map(k=>`<label>${k.toUpperCase()} · M<input data-property="${k}" type="number" value="${(p as any)[k]}" step="any"/></label>`).join('')}${o?`<label>ROTAÇÃO · °<input data-property="yaw" type="number" value="${Math.round(o.yaw*180/Math.PI)}" step="1"/></label>${o.kind==='box'||o.kind==='road'||o.kind==='helipad'?['w','h','d'].map((k,i)=>`<label>${['LARGURA','ALTURA','PROF.'][i]} · M<input data-property="${k}" type="number" min=".05" value="${(o as any)[k]}" step="any"/></label>`).join(''):''}`:''}${hill?['height','radius'].map((k,i)=>`<label>${i?'RAIO':'ALTURA'} · M<input data-property="${k}" type="number" value="${(hill as any)[k]}"/></label>`).join(''):''}${zone?`<label>RAIO · M<input data-property="radius" type="number" value="${doc.zone.radius}" min="15" max="60"/></label>`:''}</div><button class="primary">APLICAR ALTERAÇÕES</button></form><div class="inspector-actions"><button id="focus" class="secondary">CENTRALIZAR · F</button>${o?'<button id="duplicate" class="secondary">DUPLICAR</button><button id="ground-object" class="secondary">APOIAR NO TERRENO</button>':''}${o||hill?'<button id="delete" class="danger">REMOVER ELEMENTO</button>':''}</div>`;
  el('properties').onsubmit=e=>{e.preventDefault();const next=structuredClone(doc),target=o?next.objects.find(v=>v.id===o.id)!:hill?next.hills.find(v=>v.id===hill.id)!:zone?next.zone:next.spawns[spawn];root.querySelectorAll<HTMLInputElement>('[data-property]').forEach(i=>(target as any)[i.dataset.property!]=+i.value*(i.dataset.property==='yaw'?Math.PI/180:1));try{validateMapDocument(next);commit(()=>doc=next);}catch(e){status((e as Error).message,true);}};
  el('focus').onclick=()=>scene.focus(selected);if(o){el('duplicate').onclick=()=>tool({...o,id:uid()});el('ground-object').onclick=()=>commit(()=>o.y=terrainHeight(o.x,o.z,doc.hills,doc.terrain));}if(o||hill)el('delete').onclick=remove;
 } else if(selected?.startsWith('base:')){
  root.innerHTML=`<h2>ESTRUTURA ORIGINAL</h2><p class="panel-intro">${esc(selected.slice(5))}</p><p>Você pode retirar esta estrutura da sua edição e colocar um prédio da biblioteca no local.</p><button id="delete" class="danger">RETIRAR DO MAPA</button><button id="focus" class="secondary">CENTRALIZAR</button>`;el('delete').onclick=remove;el('focus').onclick=()=>scene.focus(selected);
 } else {
  root.innerHTML=`<span class="eyebrow">CONFIGURAÇÃO DA OPERAÇÃO</span><h2>SEU TERRITÓRIO.</h2><form id="map-properties"><label>NOME DO MAPA<input id="map-name" value="${esc(doc.name)}" maxlength="70" required minlength="2"/></label><label>LARGURA TOTAL · M<input id="map-width" type="number" value="${doc.limit*2}" min="192" max="1024" step="2"/></label><button class="primary">APLICAR</button></form><h3>BASES E OBJETIVO</h3><div class="entity-list">${['LYNX','EMBER','GHOST','OBJETIVO A'].map((name,i)=>`<button data-marker="${i<3?'spawn-'+i:'zone'}">${icon('target')}${name}</button>`).join('')}</div><h3>OBJETOS DA EDIÇÃO</h3><div class="entity-list object-list">${doc.objects.map(o=>`<button data-select="${o.id}">${esc(o.name)}<small>${o.kind.toUpperCase()}</small></button>`).join('')||'<p>Escolha uma peça na biblioteca.</p>'}</div>`;
  el('map-properties').onsubmit=e=>{e.preventDefault();const next={...doc,name:input('map-name').value.trim(),limit:+input('map-width').value/2};if(next.terrain&&next.terrain.size!==next.limit*2)next.terrain=createTerrainGrid(next.limit*2,next.terrain);try{validateMapDocument(next);commit(()=>doc=next);}catch(e){status((e as Error).message,true);}};
  root.querySelectorAll<HTMLElement>('[data-marker]').forEach(b=>b.onclick=()=>choose(b.dataset.marker!));root.querySelectorAll<HTMLElement>('[data-select]').forEach(b=>b.onclick=()=>choose(b.dataset.select!));
 }
}
function remove(){if(!selected)return;const id=selected;commit(()=>{if(id.startsWith('base:'))doc.hidden.push(id.slice(5));else if(id.startsWith('hill:'))doc.hills=doc.hills.filter(h=>'hill:'+h.id!==id);else doc.objects=doc.objects.filter(o=>o.id!==id);selected=null;});library();}
async function save(publish=false){if(busy)return;busy=true;document.querySelectorAll<HTMLElement>('.editor-left,.editor-right,#stage').forEach(e=>e.inert=true);for(const id of ['save','publish'])(el(id) as HTMLButtonElement).disabled=true;try{validateMapDocument(doc);if(publish){const warnings=mapWarnings(doc);if(warnings.length)throw Error(warnings.join(' '));}const {record}=await api('/api/admin/maps/save',{document:doc});doc=record.draft;if(publish)await api('/api/admin/maps/publish',{id:doc.id,revision:doc.revision});records=(await api('/api/admin/maps')).maps;dirty=false;persistLocal();el('save-state').textContent=publish?`DISPONÍVEL · R${doc.revision}`:`SALVO · R${doc.revision}`;status(publish?'Mapa disponível no seletor de operações. Partidas em andamento mantêm a versão anterior.':'Rascunho salvo no servidor.');if(tab==='maps')library();}catch(e){status((e as Error).message,true);}finally{busy=false;document.querySelectorAll<HTMLElement>('.editor-left,.editor-right,#stage').forEach(e=>e.inert=false);for(const id of ['save','publish'])(el(id) as HTMLButtonElement).disabled=false;}}
async function boot(){
 const auth=await api('/api/auth/me');if(auth.account?.role!=='admin'){app.innerHTML=`<main class="editor-gate"><span>WAR CATS / CENTRAL DE COMANDO</span><h1>ACESSO DE ADMINISTRADOR.</h1><p>Entre no jogo com sua conta administradora para criar e editar operações.</p><a href="/?account=1">ENTRAR NA CONTA ${icon('arrow')}</a></main>`;return;}
 records=(await api('/api/admin/maps')).maps;
 const last=records.find(r=>r.draft.id===localStorage.getItem('warcats-editor-last'))??[...records].sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt))[0];if(last)doc=structuredClone(last.draft);
 app.innerHTML=`<header class="editor-header"><a href="/" class="editor-brand">WAR<span>CATS</span></a><div class="editor-heading"><span>EDITOR DE OPERAÇÕES</span><h1 id="map-title"></h1></div><span id="save-state">NOVO RASCUNHO</span><nav><button id="test" class="secondary">${icon('target')} TESTAR</button><button id="save" class="secondary">SALVAR RASCUNHO</button><button id="publish" class="primary">DISPONIBILIZAR ${icon('arrow')}</button></nav></header><aside class="editor-left"><div id="palette-tabs" role="tablist">${[['objects','OBJETOS'],['buildings','PRÉDIOS'],['terrain','TERRENO'],['maps','MAPAS']].map(([id,name])=>`<button role="tab" data-tab="${id}">${name}</button>`).join('')}</div><div id="palette" class="panel-scroll"></div><footer class="editor-account">${icon('shield')} ${esc(auth.account.displayName)} · ADMIN</footer></aside><main id="stage"><canvas id="editor-canvas" aria-label="Editor tridimensional de mapas"></canvas><div class="viewport-tools"><button id="move-tool" title="Mover · G">${icon('move')} MOVER</button><button id="rotate-tool" title="Girar · R">${icon('rotate')} GIRAR</button><i></i><button id="undo" title="Desfazer · Ctrl Z">↶</button><button id="redo" title="Refazer · Ctrl Shift Z">↷</button><button id="top-view">VISTA SUPERIOR</button><button id="home-view">CENTRALIZAR</button></div><div class="viewport-caption"><b id="map-size"></b><span id="object-count"></span></div><div id="placement-help">BOTÃO DIREITO ORBITA · BOTÃO DO MEIO MOVE · RODA APROXIMA</div></main><aside class="editor-right panel-scroll"><div id="inspector"></div></aside><footer class="editor-status"><span id="editor-message" role="status">Construa sua operação. As alterações ficam no rascunho até disponibilizar.</span><span id="render-stats"></span></footer>`;
 scene=new EditorScene(el('editor-canvas') as HTMLCanvasElement);scene.onBrushStart=()=>history.push(doc);scene.onBrush=(point,dt)=>{if(busy)return;applyTerrainBrush(doc,point.x,point.z,brush,dt);scene.updateTerrain(doc);};scene.onBrushEnd=()=>{mark();draw();status('Terreno atualizado. Ctrl Z desfaz este traço.');};scene.onPick=choose;scene.onPlace=point=>{if(!pending)return;const o={...pending,id:uid(),x:point.x,y:+Math.max(point.y,terrainHeight(point.x,point.z,doc.hills,doc.terrain)).toFixed(3),z:point.z};commit(()=>doc.objects.push(o));status(`${o.name} colocado. R gira a próxima peça; Esc encerra.`);};
 scene.onTransformStart=()=>history.push(doc);scene.onTransform=(id,position,yaw)=>{const object=doc.objects.find(o=>o.id===id),hill=doc.hills.find(h=>'hill:'+h.id===id);if(object)Object.assign(object,{x:+position.x.toFixed(2),y:+position.y.toFixed(2),z:+position.z.toFixed(2),yaw:Math.atan2(Math.sin(yaw),Math.cos(yaw))});else if(hill)Object.assign(hill,{x:position.x,z:position.z});else if(id==='zone')Object.assign(doc.zone,{x:position.x,z:position.z});else if(id.startsWith('spawn-'))Object.assign(doc.spawns[+id.slice(6)],{x:position.x,z:position.z});try{validateMapDocument(doc);mark();draw();}catch(e){const previous=history.undo(doc);if(previous)doc=previous;draw();status((e as Error).message,true);}};
 el('palette-tabs').querySelectorAll<HTMLElement>('[data-tab]').forEach(b=>b.onclick=()=>{if(b.dataset.tab!=='terrain')scene.setBrush(0);tab=b.dataset.tab!;library();});
 el('save').onclick=()=>void save();el('publish').onclick=()=>void save(true);el('test').onclick=()=>{try{validateMapDocument(doc);const warnings=mapWarnings(doc);if(warnings.length)status(warnings.join(' '),true);localStorage.setItem('warcats-editor-test',JSON.stringify(doc));window.open('/?editorTest=1','_blank','noopener');}catch(e){status((e as Error).message,true);}};
 const undo=()=>{const revision=doc.revision,previous=history.undo(doc);if(previous){doc=previous;doc.revision=revision;mark();draw();library();}},redo=()=>{const revision=doc.revision,next=history.redo(doc);if(next){doc=next;doc.revision=revision;mark();draw();library();}};
 el('undo').onclick=undo;el('redo').onclick=redo;el('top-view').onclick=()=>scene.top();el('home-view').onclick=()=>scene.focus();el('move-tool').onclick=()=>scene.setMode('translate');el('rotate-tool').onclick=()=>scene.setMode('rotate');
 document.addEventListener('keydown',e=>{if(busy)return;if(e.target instanceof HTMLInputElement||e.target instanceof HTMLSelectElement||e.target instanceof HTMLTextAreaElement)return;if((e.ctrlKey||e.metaKey)&&e.code==='KeyZ'){e.preventDefault();e.shiftKey?redo():undo();}else if(e.code==='Escape')choose(null);else if(e.code==='Delete'||e.code==='Backspace')remove();else if(e.code==='KeyF')scene.focus(selected);else if(e.code==='KeyG')scene.setMode('translate');else if(e.code==='KeyR'){if(pending){pending.yaw=(pending.yaw+Math.PI/2)%(Math.PI*2);scene.setGhost(pending,doc);}else scene.setMode('rotate');}});
 window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});
 setInterval(()=>{el('render-stats').textContent=`${scene.stats.calls} CHAMADAS · ${Math.round(scene.stats.triangles/1000)} K TRIÂNGULOS`;},1000);
 draw();library();if(doc.revision)el('save-state').textContent=`RASCUNHO · R${doc.revision}`;
}
void boot().catch(e=>{app.innerHTML=`<main class="editor-gate"><h1>EDITOR INDISPONÍVEL.</h1><p>${esc(e.message)}</p><a href="/">VOLTAR AO JOGO</a><button onclick="location.reload()">TENTAR NOVAMENTE</button></main>`;});
