import test from 'node:test';import assert from 'node:assert/strict';
import {Simulation} from '../shared/simulation';import {emptyInput,type Player,type Vehicle} from '../shared/types';import {vehicleBox,VehicleSystem,createVehicles} from '../shared/vehicles';import {SupportSystem} from '../shared/support';import {getBuildPlacement} from '../shared/building';import {getMap,MAPS} from '../shared/maps';import {packState,unpackState} from '../shared/protocol';import {segmentBox,distance2} from '../shared/physics';import type {WorldBox} from '../shared/world';
const fresh=()=>new Simulation(0,471,{warmup:false});
function player(sim:Simulation,id:string,team:0|1|2=0){const p=sim.addPlayer(id,{name:id,team,weapon:'ar'});Object.assign(p,{x:0,y:0,z:0,yaw:0,protectedUntil:0});return p;}
function fixture(){const sim=fresh(),driver=player(sim,'driver'),passenger=player(sim,'passenger'),v=sim.state.vehicles[0];Object.assign(v,{x:0,y:0,z:150,yaw:0});driver.z=150;passenger.z=152;return{sim,driver,passenger,v};}
test('fleet has six separated pads, valid health/seats and roundtrip schema',()=>{for(const id of ['nordhaven','quarry','harbor'] as const){const fleet=createVehicles(id),map=getMap(id);assert.equal(fleet.length,6);for(const v of fleet){assert.ok(v.health>0);assert.equal(v.seats.length,v.kind==='jeep'?4:6);const a=vehicleBox(v);assert.ok(!map.boxes.some(b=>Math.abs(a.x-b.x)<(a.w+b.w)/2&&Math.abs(a.z-b.z)<(a.d+b.d)/2&&a.y+a.h/2>b.y-b.h/2+.03&&a.y-a.h/2<b.y+b.h/2-.03),`${id} ${v.id} spawn intersects terrain`);assert.ok(fleet.every(o=>o.id===v.id||distance2(o,v)>=11));}}const sim=fresh(),p=player(sim,'pilot');p.skin='desert';p.supportPoints=60;assert.deepEqual(unpackState(packState(sim.state)).vehicles,sim.state.vehicles);assert.equal(unpackState(packState(sim.state)).players.pilot.skin,'desert');});
test('E enters once, blocks hostile/full/moving vehicles, and exiting respects speed/altitude',()=>{const{sim,driver,passenger,v}=fixture();assert.ok(sim.vehicles.board(driver,v));assert.equal(driver.vehicleSeat,0);assert.ok(sim.vehicles.board(passenger,v));assert.equal(passenger.vehicleSeat,1);const enemy=player(sim,'enemy',1);enemy.z=150;assert.equal(sim.vehicles.board(enemy,v),false);v.speed=8;sim.vehicles.toggle(driver,[]);assert.equal(driver.vehicleId,v.id);v.speed=0;v.y=8;sim.vehicles.toggle(driver,[]);assert.equal(driver.vehicleId,v.id);v.y=0;sim.vehicles.toggle(driver,[]);assert.equal(driver.vehicleId,null);assert.equal(v.seats[0],null);});
test('ground vehicle accelerates independently of aim and a high-speed ram explodes without tunneling',()=>{const{sim,driver,v}=fixture();sim.vehicles.board(driver,v);const input={...emptyInput(),forward:1,yaw:Math.PI/2};const inputs=new Map([[driver.id,input]]);const wall:WorldBox={id:'wall',x:0,y:2,z:130,w:20,h:4,d:.2,material:'concrete'};for(let i=0;i<150;i++)sim.vehicles.tick(1/30,inputs,[wall]);assert.ok(v.z>132);assert.ok(v.z<150);assert.equal(v.yaw,0);assert.equal(v.health,0);assert.ok(Math.abs(v.speed)<.01);assert.ok(sim.state.events.some(e=>e.type==='explosion'&&e.target===v.id));});
test('a slow jeep bump into cover stops the hull without destroying it',()=>{const{sim,driver,v}=fixture();sim.vehicles.board(driver,v);Object.assign(v,{z:134,vx:0,vz:-4.5,speed:4.5,yaw:0});const wall:WorldBox={id:'wall',x:0,y:2,z:130,w:20,h:4,d:.2,material:'concrete'};for(let i=0;i<40;i++)sim.vehicles.tick(1/30,new Map([[driver.id,emptyInput()]]),[wall]);assert.ok(v.health>v.maxHealth*.9);assert.ok(v.z>132);assert.equal(v.health,v.maxHealth);});
test('helicopter climbs, flares to land, and keeps its pilot out of objective scoring',()=>{const sim=fresh(),p=player(sim,'pilot'),v=sim.state.vehicles.find(v=>v.kind==='helicopter'&&v.team===0)!;Object.assign(v,{x:0,z:0,y:0});assert.ok(sim.vehicles.board(p,v));const inputs=new Map([[p.id,{...emptyInput(),ascend:true}]]);for(let i=0;i<60;i++)sim.vehicles.tick(1/30,inputs,[]);assert.ok(v.y>8);assert.ok(v.fuel<100);(sim as any).controlZone(1);assert.deepEqual(sim.state.presence,[0,0,0]);assert.equal(p.captures,0);Object.assign(v,{y:5.2,vy:-1.1,vx:0,vz:0,pitch:0,roll:0,collective:.5,landed:false,groundHeight:0});for(let i=0;i<150;i++){const alt=v.y;inputs.set(p.id,{...emptyInput(),brake:true,descend:alt>1.8,ascend:alt<1.2&&v.vy<-.9});sim.vehicles.tick(1/30,inputs,[]);}assert.ok(v.y<0.2);assert.ok(v.health>0);assert.ok(v.landed);});
test('diving a helicopter into the ground destroys the airframe',()=>{const sim=fresh(),p=player(sim,'pilot'),v=sim.state.vehicles.find(v=>v.kind==='helicopter'&&v.team===0)!;Object.assign(v,{x:0,z:0,y:0});p.x=0;p.z=0;p.y=0;assert.ok(sim.vehicles.board(p,v));Object.assign(v,{y:36,vy:-14,vx:0,vz:0,rotorSpeed:1,collective:.08,landed:false,groundHeight:0,pitch:0,roll:0});const inputs=new Map([[p.id,{...emptyInput(),descend:true}]]);for(let i=0;i<90&&v.health>0;i++)sim.vehicles.tick(1/30,inputs,[]);assert.equal(v.health,0);assert.ok(sim.state.events.some(e=>e.type==='explosion'));});
test('a useful passenger delivery pays once per life with survival bonus, repeated pickup pays nothing',()=>{const{sim,driver,passenger,v}=fixture();sim.vehicles.board(driver,v);sim.vehicles.board(passenger,v);const before=driver.credits;v.z=sim.state.zone.z;v.x=sim.state.zone.x;v.distance=160;sim.vehicles.tick(.01,new Map(),[]);sim.vehicles.toggle(passenger,[]);assert.equal(driver.credits-before,300);assert.equal(driver.transports,1);assert.equal(driver.supportPoints,60);assert.equal(driver.earned,300);sim.state.time+=10.1;sim.vehicles.tick(.01,new Map(),[]);assert.equal(driver.credits-before,450);assert.equal(driver.supportPoints,80);passenger.x=v.x;passenger.z=v.z;sim.vehicles.board(passenger,v);v.distance+=200;sim.vehicles.toggle(passenger,[]);assert.equal(driver.credits-before,450);});
test('short trips, circular farming, and preparation do not earn transport cash',()=>{for(const mode of ['short','circle','warmup']){const{sim,driver,passenger,v}=fixture();if(mode==='warmup')sim.state.phase='warmup';sim.vehicles.board(driver,v);sim.vehicles.board(passenger,v);const before=driver.credits;if(mode!=='circle'){v.z=0;v.x=0;}v.distance=mode==='short'?25:200;sim.vehicles.tick(.01,new Map(),[]);sim.vehicles.toggle(passenger,[]);assert.equal(driver.credits,before,mode);}});
test('vehicle destruction removes occupants, kills them and respawns an empty fleet vehicle',()=>{const{sim,driver,passenger,v}=fixture();sim.vehicles.board(driver,v);sim.vehicles.board(passenger,v);const enemy=player(sim,'enemy',1);sim.vehicles.damage(v,1000,enemy.id);assert.equal(v.health,0);assert.equal(driver.vehicleId,null);assert.equal(passenger.state,'dead');assert.ok(v.seats.every(x=>x===null));sim.state.time=36;sim.vehicles.tick(.01,new Map(),[]);assert.equal(v.health,v.maxHealth);assert.equal(v.y,0);});
test('rapid spotting requires line of sight, expires and never tracks through walls',()=>{const sim=fresh(),p=player(sim,'spotter'),q=player(sim,'target',1);q.z=-30;p.pitch=0;sim.support.spot(p,[]);assert.equal(sim.state.spots.length,1);const spot=sim.state.spots[0],oldX=spot.x;const wall:WorldBox={id:'wall',x:0,y:2,z:-15,w:30,h:4,d:.2,material:'concrete'};q.x=4;sim.support.tick(.1,[wall]);assert.equal(spot.x,oldX);sim.state.time=2;sim.state.spots=[];sim.support.spot(p,[wall]);assert.equal(sim.state.spots.length,0);sim.state.time=4.1;sim.support.tick(.1,[]);assert.equal(sim.state.spots.length,0);});
test('near misses suppress once per bullet, respect walls and rate-limit rewards',()=>{const sim=fresh(),p=player(sim,'shooter'),q=player(sim,'target',1);q.x=1.2;q.z=-10;const b={id:1,x:0,y:1.4,z:0,owner:p.id,team:p.team,vx:0,vy:0,vz:-900,life:1,damage:30,distance:0,weapon:'ar' as const};const before=p.credits;sim.support.nearMiss(b,{x:0,y:1.4,z:0},{x:0,y:1.4,z:-20},[]);assert.ok(q.suppression>0);assert.equal(p.credits-before,12);const amount=q.suppression;sim.support.nearMiss(b,{x:0,y:1.4,z:0},{x:0,y:1.4,z:-20},[]);assert.equal(q.suppression,amount);sim.support.nearMiss({...b,id:2},{x:0,y:1.4,z:0},{x:0,y:1.4,z:-20},[]);assert.equal(p.credits-before,12);q.suppression=0;const wall:WorldBox={id:'wall',x:.6,y:1.5,z:-10,w:.1,h:3,d:10,material:'concrete'};sim.support.nearMiss({...b,id:3},{x:0,y:1.4,z:0},{x:0,y:1.4,z:-20},[wall]);assert.equal(q.suppression,0);});
test('spot assist rewards an ally kill once and no reward for own kill',()=>{const sim=fresh(),p=player(sim,'spotter'),ally=player(sim,'killer'),q=player(sim,'target',1);q.z=-25;sim.support.spot(p,[]);const before=p.credits;sim.support.assists(q,ally,new Set());assert.equal(p.credits-before,80);assert.equal(p.assists,1);sim.support.assists(q,ally,new Set());assert.equal(p.credits-before,80);});
test('skin messages cannot write arbitrary state, and warmup transition clears boarded positions',()=>{const sim=new Simulation(0),p=player(sim,'p');sim.setSkin(p.id,'urban');assert.equal(p.skin,'urban');sim.setSkin(p.id,'constructor');assert.equal(p.skin,'urban');const v=sim.state.vehicles[0];p.x=v.x;p.z=v.z;sim.vehicles.board(p,v);sim.state.time=sim.state.phaseEndsAt;sim.tick(.01);assert.equal(p.vehicleId,null);assert.equal(sim.state.phase,'active');assert.equal(sim.state.spots.length,0);});
test('preparation with a knife or secondary equipped preserves both paid weapon slots',()=>{for(const slot of [1,2] as const){const sim=new Simulation(0),p=sim.addPlayer('p',{name:'P',team:0,weapon:'awm',secondary:'rpg'});(sim as any).equipSlot(p,slot);const cash=p.credits;sim.state.time=sim.state.phaseEndsAt;sim.tick(.01);assert.equal(p.primary,'awm');assert.equal(p.secondary,'rpg');assert.equal(p.weapon,'awm');assert.equal(p.credits,cash);assert.equal(p.primaryAmmo,5);assert.equal(p.secondaryAmmo,1);}});

test('construction preview rejects occupied vehicle space on both client and server',()=>{const sim=fresh(),p=player(sim,'builder');let placement=getBuildPlacement(p,sim.state);for(let z=35;z<100&&!placement.valid;z+=5){p.z=z;placement=getBuildPlacement(p,sim.state);}assert.ok(placement.valid);const v=sim.state.vehicles[0];v.x=placement.x;v.z=placement.z;v.y=0;assert.equal(getBuildPlacement(p,sim.state).valid,false);assert.match(getBuildPlacement(p,sim.state).reason,/obstáculo/);});

test('HALO exit from a hovering helicopter leaves the pilot in free fall',()=>{
  const sim=fresh(),p=player(sim,'pilot'),v=sim.state.vehicles.find(item=>item.kind==='helicopter'&&item.team===0)!;
  Object.assign(v,{x:40,z:40,y:0,speed:0,groundHeight:0,vy:0});p.x=40;p.z=40;p.y=0;
  assert.ok(sim.vehicles.board(p,v));
  Object.assign(v,{y:36,groundHeight:0,speed:1,vy:0});
  sim.vehicles.toggle(p,[]);
  assert.equal(p.vehicleId,null);assert.ok(p.y>20);assert.equal(p.parachute,false);assert.equal(p.grounded,false);
});
