import { CLASSES, CLASS_IDS } from '../../shared/classes';
import { icon } from './icons';
import { featureIcon } from './feature-icons';

const controls = [
  ['W A S D', 'Mover / dirigir'], ['MOUSE', 'Olhar'], ['CLIQUE', 'Atirar / confirmar construção'],
  ['BOTÃO DIR.', 'Mirar / cancelar construção'], ['1 / 2 / 3', 'Primária / secundária / faca'],
  ['SHIFT', 'Correr / estabilizar a mira'], ['ESPAÇO', 'Pular / abrir paraquedas / subir helicóptero'], ['C / CTRL', 'Agachar / descer helicóptero'],
  ['Z', 'Deitar / levantar'], ['X', 'Frear e estabilizar helicóptero'], ['E', 'Embarcar / desembarcar / salto HALO'], ['R', 'Recarregar / girar barricada'], ['H', 'Primeiros socorros'],
  ['G', 'Granada / bolsa do suporte'], ['F', 'Reanimar / abastecer / reparar / torre de inserção'], ['B', 'Pré-visualizar / empilhar barricada'],
  ['Q', 'Marcar inimigo visível / posição'], ['M', 'Mapa tático'], ['TAB', 'Placar e apoio'], ['O', 'Loja de armas'],
  ['RODA', 'Alternar ampliação da mira'], ['ESC', 'Menu da operação'],
];

export function fieldMarkup(mapName: string) {
  return `<div class="manual-heading"><span class="section-kicker">BRIEFING / ${mapName.toUpperCase()}</span><h2>ENTRE COM<br/>UM PLANO.</h2><p>Três equipes. Um território. Prepare seu equipamento, leve os aliados até a zona e mantenha a maioria para vencer.</p><div class="manual-cycle"><span>15 S · PREPARAÇÃO</span>${icon('arrow')}<span>10 MIN · OPERAÇÃO</span>${icon('arrow')}<span>12 S · RESULTADO</span>${icon('arrow')}<span>8 S · TROCA DE MAPA</span></div><button id="manual-back" class="text-button">VOLTAR À OPERAÇÃO ${icon('arrow')}</button></div><div class="manual-sections">
    <article><span>${icon('flag')} 01 / DOMINE</span><h3>PRESENÇA É PODER.</h3><p>A maioria precisa se manter por 5 segundos para capturar a zona A. Depois, recebe 1 ponto a cada 2 segundos. Empates interrompem a pontuação. Vence quem chega a 100 pontos; no limite de tempo, vale o placar. Operadores na zona quente contam em dobro.</p><p>Fique no círculo para ganhar 6 CR/s. O círculo menor muda a cada 45 segundos e paga 12 CR/s. Eliminações pagam 300 CR no campo, 1.500 na zona e 3.000 na zona quente — metade pela sua posição, metade pela do alvo. Headshot vale 350 de base. TAB mostra baixas, mortes, assistências e o dinheiro ganho nesta rodada.</p></article>
    <article><span>${icon('medical')} 02 / SOBREVIVA</span><h3>SUA VIDA NÃO REGENERA.</h3><p>Projéteis têm velocidade e queda. Mirar e agachar reduzem a dispersão. Z alterna deitar: rasteje devagar e ganhe estabilidade para tiros de precisão. Dano ou disparos interrompem os primeiros socorros. Use cobertura para recarregar; tiros próximos aumentam a supressão.</p><p>Leve primária, secundária e faca. Configure mira, cano e empunhadura no arsenal. A óptica usa ampliação real; a roda alterna o zoom disponível. A pintura altera somente a aparência.</p></article>
    <article><span>${featureIcon('spot')} 03 / APOIE</span><h3>A EQUIPE VÊ COM VOCÊ.</h3><p>Use Q sobre um inimigo visível para compartilhar sua última posição por 4 segundos e ganhar 20 CR. A marca não acompanha o alvo através de paredes. Sem contato visível, Q marca o terreno.</p><p>Se um aliado eliminar o marcado, você recebe assistência de marcação: 80 CR no campo, 400 na zona e 800 na zona quente. Dano recente, supressão e inserção de aliado também contam como assistência. Segure F para reanimar: 90 CR no campo, 450 na zona e 900 na zona quente.</p></article>
    <article><span>${featureIcon('transport')} 04 / TRANSPORTE</span><h3>LEVE A EQUIPE ADIANTE.</h3><p>Jeeps levam 4 operadores e helicópteros, 6. Aproxime-se de um veículo aliado com assento livre e use E. O primeiro assento dirige; os demais embarcam como passageiros. WASD dirige o jeep; X freia. No helicóptero não há hover mágico: WASD inclina o disco, Espaço sobe o coletivo, C desce, X corta a velocidade. Soltar os comandos mantém a inércia e o aparelho perde altitude.</p><p>Pouse nivelado, devagar e em piso plano — tombamento, mergulho ou corrida no solo destroem a aeronave. O jeep explode se bater forte ou parar numa ladeira extrema. Para sair no solo, reduza a menos de 14,4 km/h e pouse. Acima de 12 m, E faz um salto HALO: abra o paraquedas no ar. Sem vela, a queda causa dano grave.</p></article>
    <article><span>${featureIcon('pilot')} 05 / LOGÍSTICA</span><h3>O DESEMBARQUE CONTA.</h3><p>Leve um aliado de mais de 60 m além da borda da zona até o objetivo: são necessários 75 m percorridos, 65 m de deslocamento e desembarque a até 18 m da borda da zona. O transporte válido rende 300 CR e 60 XP ao motorista, uma vez por vida do passageiro.</p><p>Se o aliado sobreviver por 10 segundos a até 35 m da borda da zona, você recebe mais 150 CR e 20 XP. Se ele eliminar alguém nos 45 segundos seguintes, você ganha assistência de inserção. A confirmação aparece na tela; deslocamentos curtos não contam.</p></article>
    <article><span>${icon('hammer')} 06 / CONSTRUA</span><h3>ESCOLHA SUA COBERTURA.</h3><p>Use B para visualizar a barricada antes de gastar. R gira; clique confirma e inicia a obra. A posição precisa estar livre. Mover-se ou sofrer dano interrompe a construção.</p><p>O kit de assalto constrói por 200 CR em 4 segundos, com limite de 4 barricadas. O engenheiro paga 120 CR, constrói em 2,4 segundos e mantém até 6. Compre armas na base ou durante o reaparecimento.</p></article>
    <article><span>${icon('terrain')} 07 / INSERÇÃO</span><h3>TORRE, HALO E PARAQUEDAS.</h3><p>Em cada base há uma torre de inserção. Segure F na plataforma para subir ao deck de 28 m. Caminhe até a borda aberta e salte. Espaço abre a vela; WASD guia a queda. Impactos acima de 12 m/s sem paraquedas gastam colete e vida.</p><p>O helicóptero também serve de inserção: suba, estabilize e use E para o salto HALO. Na preparação, use a torre para treinar a abertura da vela.</p></article>
    <section class="manual-classes"><div class="manual-subheading"><span>FUNÇÕES DO OPERADOR</span><small>ESCOLHA NO ARSENAL ANTES DA OPERAÇÃO</small></div><div>${CLASS_IDS.map(id => `<article><h4>${id === 'assault' ? 'ASSALTO' : CLASSES[id].name}</h4><p>${CLASSES[id].note}</p></article>`).join('')}</div></section>
    <section class="manual-controls"><div class="manual-subheading"><span>CONTROLES DE CAMPO</span><small>TECLADO E MOUSE</small></div><div class="control-grid">${controls.map(([key, label]) => `<div><kbd>${key}</kbd><span>${label}</span></div>`).join('')}</div></section>
  </div>`;
}
