import assert from 'node:assert/strict';
import { mkdir, writeFile } from 'node:fs/promises';
import { chromium } from 'playwright';

const base = process.env.TEST_URL || 'http://localhost:5173';
const browser = await chromium.launch({ channel: 'chrome', headless: true });
const artifacts = new URL('../artifacts/', import.meta.url);
await mkdir(artifacts, { recursive: true });
const errors = [];
const results = [];
let assertionCount = 0;
function check(condition, label) { assert.ok(condition, label); assertionCount++; results.push(label); console.log('PASS', label); }
const track = page => {
  page.on('pageerror', e => errors.push(e.message));
  page.on('console', m => { if (m.type() === 'error') errors.push(m.text()); });
};
const diagnostics = page => page.evaluate(() => ({ stats: window.__WAR_CATS__?.stats, player: window.__WAR_CATS__?.player }));
const ready = page => page.waitForFunction(() => !document.getElementById('loading'), { timeout: 15000 });
const screenshot = (page, name) => page.screenshot({ path: new URL(name, artifacts).pathname, fullPage: true });

try {
  const context = await browser.newContext({ viewport: { width: 1440, height: 900 }, deviceScaleFactor: 1 });
  const page = await context.newPage(); track(page); await page.goto(base); await ready(page);
  check(await page.getByRole('heading', { name: 'TRÊS EQUIPES. UM TERRITÓRIO.' }).isVisible(), 'Lobby displays the operation and start action');
  await screenshot(page, 'lobby.png');
  await page.getByRole('button', { name: 'ARSENAL', exact: true }).click();
  await page.locator('[data-weapon="smg"]').click();
  check(await page.locator('[data-weapon="smg"]').getAttribute('aria-pressed') === 'true', 'Arsenal selection updates accessibly');
  await screenshot(page, 'arsenal.png');
  await page.getByRole('button', { name: 'CONFIRMAR EQUIPAMENTO' }).click();
  check((await page.locator('#loadout-name').innerText()).includes('VMP-9'), 'Chosen weapon returns to the deploy panel');
  await page.getByRole('button', { name: 'Abrir configurações' }).click();
  await page.selectOption('#quality', 'low');
  await page.locator('#sensitivity').fill('1.25');
  await page.getByRole('button', { name: 'SALVAR E VOLTAR' }).click();
  await page.reload(); await ready(page);
  check(await page.evaluate(() => JSON.parse(localStorage.getItem('warcats-settings')).quality === 'low'), 'Settings survive reload');
  await page.getByRole('button', { name: 'MANUAL DE CAMPO', exact: true }).click();
  check(await page.getByText('SUA VIDA NÃO REGENERA.').isVisible(), 'Field manual documents realistic health and cooperation');
  await screenshot(page, 'manual.png');
  await page.getByRole('button', { name: 'VOLTAR À OPERAÇÃO' }).click();
  await page.fill('#callsign', 'Tester');
  await page.getByRole('button', { name: /ENTRAR EM OPERAÇÃO/ }).click();
  await page.waitForTimeout(700);
  const first = await diagnostics(page);
  check(first.stats.mode === 'local' && first.player.weapon === 'smg', 'Local match deploys with selected weapon');
  check(await page.evaluate(() => !!document.pointerLockElement), 'Desktop pointer lock is active');
  await screenshot(page, 'gameplay.png');
  await page.keyboard.down('KeyW'); await page.waitForTimeout(600); await page.keyboard.up('KeyW');
  const moved = await diagnostics(page);
  check(Math.hypot(moved.player.x - first.player.x, moved.player.z - first.player.z) > 1.5, 'WASD moves the simulated operator');
  await page.mouse.down(); await page.waitForTimeout(450); await page.mouse.up(); await page.waitForTimeout(100);
  const shot = await diagnostics(page);
  check(shot.player.ammo < moved.player.ammo, 'Mouse fire consumes live ammunition');
  await page.keyboard.press('KeyR'); await page.waitForTimeout(100);
  check((await diagnostics(page)).player.reloadUntil > 0, 'Reload displays a timed action');
  await page.waitForTimeout(2000);
  check((await diagnostics(page)).player.ammo === 35, 'Magazine refills after weapon-specific reload time');
  await page.keyboard.press('KeyG'); await page.waitForTimeout(100);
  check((await diagnostics(page)).player.grenades === 1, 'Grenade control consumes one grenade');
  await page.keyboard.down('KeyC'); await page.waitForTimeout(100);
  check((await diagnostics(page)).player.crouch, 'Crouch control changes player stance');
  await page.keyboard.up('KeyC');
  await page.keyboard.press('KeyM');
  check(await page.locator('#map-layer').isVisible(), 'Tactical map opens with M');
  await screenshot(page, 'tactical-map.png');
  await page.keyboard.press('KeyM');
  await page.keyboard.down('Tab');
  check(await page.getByRole('heading', { name: 'RELATÓRIO DA OPERAÇÃO' }).isVisible(), 'Scoreboard shows all three teams');
  await page.keyboard.up('Tab');
  await page.keyboard.press('Escape'); await page.waitForTimeout(150);
  check(await page.getByRole('button', { name: 'VOLTAR AO COMBATE' }).isVisible(), 'Escape opens the operation menu');
  const pausedTime = await page.evaluate(() => window.__WAR_CATS__.state.time); await page.waitForTimeout(300);
  check(await page.evaluate(t => window.__WAR_CATS__.state.time === t, pausedTime), 'Local pause freezes the simulation');
  await page.getByRole('button', { name: 'VOLTAR AO COMBATE' }).click(); await page.waitForTimeout(200);
  check(!(await diagnostics(page)).stats.paused, 'Resume restores gameplay');
  await page.keyboard.press('Escape'); await page.waitForTimeout(100); await page.getByRole('button', { name: 'SAIR DA OPERAÇÃO' }).click();
  check(await page.locator('#menu').isVisible(), 'Leaving a match restores the lobby');

  // Two independent browser contexts are real players, not duplicated simulated actors.
  await page.getByRole('button', { name: 'MULTIPLAYER', exact: true }).click();
  await page.getByRole('button', { name: /ENTRAR EM OPERAÇÃO/ }).click();
  await page.getByRole('button', { name: 'VOLTAR AO COMBATE' }).waitFor();
  const online = await diagnostics(page); check(online.stats.mode === 'online' && online.stats.room?.length === 6, 'Online room is created by the server');
  const room = online.stats.room;
  const otherContext = await browser.newContext({ viewport: { width: 1280, height: 800 }, deviceScaleFactor: 1 });
  const other = await otherContext.newPage(); track(other);
  await other.goto(`${base}/?room=${room}`); await ready(other); await other.fill('#callsign', 'Second player');
  await other.locator('[data-team="1"]').click(); await other.getByRole('button', { name: /ENTRAR EM OPERAÇÃO/ }).click();
  await other.getByRole('button', { name: 'VOLTAR AO COMBATE' }).waitFor();
  check((await diagnostics(other)).stats.room === room, 'Invite joins a second browser to the same room');
  await page.bringToFront(); await page.waitForTimeout(200);
  check(await page.evaluate(() => Object.values(window.__WAR_CATS__.state.players).filter(p => !p.bot).length === 2), 'Both browsers receive the two human players');
  await page.getByRole('button', { name: 'VOLTAR AO COMBATE' }).click();
  const onlineStart = (await diagnostics(page)).player;
  await page.keyboard.down('KeyW'); await page.waitForTimeout(600); await page.keyboard.up('KeyW');
  const onlineMoved = (await diagnostics(page)).player;
  check(Math.hypot(onlineMoved.x - onlineStart.x, onlineMoved.z - onlineStart.z) > 1, 'Online prediction and authoritative movement work together');
  await page.mouse.down(); await page.waitForTimeout(400); await page.mouse.up(); await page.waitForTimeout(100);
  check((await diagnostics(page)).player.ammo < 35, 'Online shots are acknowledged by server ammunition');
  await screenshot(page, 'multiplayer.png');
  await page.keyboard.press('Escape'); await page.waitForTimeout(100); await page.getByRole('button', { name: 'SAIR DA OPERAÇÃO' }).click();
  await otherContext.close();

  // Responsive lobby and real touch input.
  const mobileContext = await browser.newContext({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 1, isMobile: true, hasTouch: true });
  const mobile = await mobileContext.newPage(); track(mobile); await mobile.goto(base); await ready(mobile);
  check(await mobile.evaluate(() => document.documentElement.scrollWidth <= innerWidth), '390px layout has no horizontal overflow');
  await screenshot(mobile, 'mobile-lobby.png');
  await mobile.getByRole('button', { name: /ENTRAR EM OPERAÇÃO/ }).tap(); await mobile.waitForTimeout(200);
  check(await mobile.locator('.touch-fire').isVisible(), 'Touch combat controls are visible');
  const beforeTouch = (await diagnostics(mobile)).player.ammo;
  const fireBounds = await mobile.locator('.touch-fire').boundingBox();
  const mobileCdp = await mobileContext.newCDPSession(mobile);
  await mobileCdp.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ x: fireBounds.x + fireBounds.width / 2, y: fireBounds.y + fireBounds.height / 2 }] });
  await mobile.waitForTimeout(200);
  await mobileCdp.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] });
  check((await diagnostics(mobile)).player.ammo < beforeTouch, 'Touch fire operates the same ammunition simulation');
  await screenshot(mobile, 'mobile-gameplay.png');
  await mobile.getByRole('button', { name: 'Pausar jogo' }).tap();
  check(await mobile.getByRole('button', { name: 'VOLTAR AO COMBATE' }).isVisible(), 'Touch pause is reachable');
  await mobileContext.close();
  check(errors.length === 0, `No browser errors: ${errors.join('; ')}`);
  const report = { passed: assertionCount, checks: results, browserErrors: errors, desktopPerformance: first.stats, viewport: '1440×900', note: 'Local machine in Chrome headless; not a cross-device benchmark.' };
  await writeFile(new URL('browser-report.json', artifacts), JSON.stringify(report, null, 2));
  console.log(JSON.stringify(report, null, 2));
} finally { await browser.close(); }
