import { chromium } from 'playwright';
import { mkdir } from 'node:fs/promises';
const browser = await chromium.launch({ channel: 'chrome', headless: true });
const page = await browser.newPage({ viewport: { width: 1440, height: 900 }, deviceScaleFactor: 1 });
page.on('pageerror', e => console.log('PAGE ERROR:', e.message));
page.on('console', m => { if (m.type() === 'error' || m.type() === 'warning') console.log(m.type(), m.text()); });
await page.goto('http://localhost:5173');
await page.waitForTimeout(4000);
await mkdir('artifacts', { recursive: true });
await page.screenshot({ path: 'artifacts/lobby.png' });
console.log('INITIAL', await page.evaluate(() => ({ title: document.title, text: document.body.innerText.slice(-700), diagnostics: window.__WAR_CATS__?.stats })));
await page.getByRole('button', { name: /ENTRAR EM OPERAÇÃO/ }).click();
await page.waitForTimeout(1500);
console.log('PLAY', await page.evaluate(() => ({ stats: window.__WAR_CATS__?.stats, player: window.__WAR_CATS__?.player, locked: !!document.pointerLockElement })));
await page.screenshot({ path: 'artifacts/gameplay.png' });
await page.keyboard.down('KeyW');
await page.keyboard.down('ShiftLeft');
await page.waitForTimeout(4500);
await page.keyboard.up('KeyW');
await page.keyboard.up('ShiftLeft');
await page.screenshot({ path: 'artifacts/approach.png' });
console.log('MOVED', await page.evaluate(() => ({ stats: window.__WAR_CATS__?.stats, player: window.__WAR_CATS__?.player })));
await browser.close();
