import assert from 'node:assert/strict';
import { chromium } from 'playwright';
import { writeFile } from 'node:fs/promises';
const base = process.env.TEST_URL || 'http://localhost:3002';
const indexResponse = await fetch(base, { headers: { 'Accept-Encoding': 'br' } });
assert.equal(indexResponse.headers.get('content-encoding'), 'br');
const html = await indexResponse.text();
const jsPath = html.match(/src="([^"]+\.js)"/)[1];
const asset = await fetch(new URL(jsPath, base), { headers: { 'Accept-Encoding': 'gzip' } });
assert.equal(asset.status, 200); assert.equal(asset.headers.get('content-encoding'), 'gzip');
const browser = await chromium.launch({ channel: 'chrome', headless: true });
const page = await browser.newPage({ viewport: { width: 1440, height: 900 }, deviceScaleFactor: 1 });
const errors = [];
page.on('pageerror', e => errors.push(e.message));
page.on('console', m => { if (m.type() === 'error') errors.push(m.text()); });
try {
  await page.goto(base); await page.waitForFunction(() => !document.getElementById('loading'));
  assert.equal(await page.evaluate(() => typeof window.__WAR_CATS__), 'undefined');
  await page.screenshot({ path: 'artifacts/production-lobby.png' });
  await page.getByRole('button', { name: 'ARSENAL', exact: true }).click();
  await page.waitForTimeout(200); await page.screenshot({ path: 'artifacts/production-arsenal.png' });
  await page.getByRole('button', { name: 'CONFIRMAR EQUIPAMENTO' }).click();
  await page.getByRole('button', { name: /ENTRAR EM OPERAÇÃO/ }).click(); await page.waitForTimeout(600);
  await page.keyboard.press('Escape');await page.locator('#settings-shop').click();await page.locator('[data-shop-muzzle="comp"]').click();await page.locator('#shop-kit-buy').click();
  await page.waitForFunction(()=>document.querySelector('#shop-feedback')?.textContent?.includes('acessórios aplicados'));assert.match(await page.locator('#shop-cash').innerText(),/9[.,]820/);
  await page.locator('#shop-resume').click();
  const ammoBefore = Number(await page.locator('#ammo').textContent());
  await page.mouse.down(); await page.waitForTimeout(350); await page.mouse.up(); await page.waitForTimeout(100);
  assert.ok(Number(await page.locator('#ammo').textContent()) < ammoBefore);
  await page.keyboard.press('KeyR'); await page.waitForTimeout(2600);
  assert.equal(Number(await page.locator('#ammo').textContent()), 30);
  await page.keyboard.down('KeyW'); await page.keyboard.down('ShiftLeft'); await page.waitForTimeout(4000); await page.keyboard.up('ShiftLeft'); await page.keyboard.up('KeyW');
  await page.keyboard.down('KeyA'); await page.waitForTimeout(3000); await page.keyboard.up('KeyA');
  await page.keyboard.down('KeyW'); await page.waitForTimeout(2200); await page.keyboard.up('KeyW');
  await page.screenshot({ path: 'artifacts/production-combat.png' });
  await page.keyboard.press('Escape'); await page.getByRole('button', { name: 'SAIR DA OPERAÇÃO' }).click();
  await page.getByRole('button', { name: 'MULTIPLAYER', exact: true }).click();
  await page.getByRole('button', { name: /ENTRAR EM OPERAÇÃO/ }).click();
  await page.getByRole('button', { name: 'VOLTAR AO COMBATE' }).waitFor();
  assert.match(await page.locator('.room-share b').innerText(), /^[A-F0-9]{6}$/);
  await page.getByRole('button', { name: 'VOLTAR AO COMBATE' }).click(); await page.waitForTimeout(400);
  assert.ok((await page.locator('#network-label').innerText()).includes('MS'));
  await page.keyboard.press('Escape'); await page.getByRole('button', { name: 'SAIR DA OPERAÇÃO' }).click();
  assert.deepEqual(errors, []);
  const report = { production: true, passed: ['Brotli HTML', 'Gzip JS', 'No development diagnostics exposed', 'Local deployment', 'Production attachment purchase and paused acknowledgement', 'Mouse firing', 'Timed reload', 'World movement', 'Pause and return to menu', 'Production WebSocket room creation', 'Production online session', 'No browser errors'], browserErrors: errors };
  await writeFile('artifacts/production-report.json', JSON.stringify(report, null, 2));
  console.log(JSON.stringify(report, null, 2));
} finally { await browser.close(); }
