import '@fontsource/barlow-condensed/700.css';import '@fontsource/ibm-plex-mono/400.css';import '@fontsource/ibm-plex-sans/400.css';import './asset-gallery.css';
type Asset={name:string;category:string;url:string;source?:string;preview?:string;bytes:number};
type Library={assets:Asset[];spent:number;remaining:number;generated:number};
const root=document.getElementById('catalog')!;
root.innerHTML='<main><p class="eyebrow">WAR CATS / ACERVO</p><h1>PREPARANDO O ACERVO.</h1><p role="status">Carregando materiais de campo…</p><a href="/">Voltar ao jogo</a></main>';
const escape=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
let disposeViewer:(()=>void)|undefined;
async function viewer(asset:Asset){
 const dialog=document.createElement('dialog');dialog.className='model-dialog';dialog.innerHTML=`<header><div><p class="eyebrow">MODELO 3D / INSPEÇÃO</p><h2>${escape(asset.name)}</h2></div><button class="close" aria-label="Fechar inspeção">×</button></header><div class="model-stage"><p role="status">Preparando modelo…</p></div><footer><span>ARRASTE PARA GIRAR · ROLE PARA APROXIMAR</span><a href="${asset.url}" download>BAIXAR GLB ↗</a></footer>`;document.body.append(dialog);dialog.showModal();
 const previousFocus=document.activeElement as HTMLElement|null;let closed=false;const close=()=>{closed=true;disposeViewer?.();disposeViewer=undefined;dialog.remove();previousFocus?.focus();};dialog.querySelector('button')!.onclick=close;dialog.addEventListener('cancel',e=>{e.preventDefault();close();});dialog.addEventListener('click',e=>{if(e.target===dialog)close();});
 try{
 const [THREE,{GLTFLoader},{OrbitControls}]=await Promise.all([import('three'),import('three/addons/loaders/GLTFLoader.js'),import('three/addons/controls/OrbitControls.js')]);if(closed)return;
 const stage=dialog.querySelector('.model-stage') as HTMLElement,renderer=new THREE.WebGLRenderer({antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.2;stage.append(renderer.domElement);
 const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(38,1,.01,100),controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.enablePan=false;controls.minDistance=.7;controls.maxDistance=6;scene.add(new THREE.HemisphereLight(0xe9f3ed,0x343b2d,2.5));const key=new THREE.DirectionalLight(0xffefd4,3);key.position.set(3,5,4);scene.add(key);const rim=new THREE.DirectionalLight(0xadd1e7,2);rim.position.set(-3,2,-4);scene.add(rim);
 let frame=0,model:import('three').Group|undefined;
 const resize=()=>{renderer.setSize(stage.clientWidth,stage.clientHeight);camera.aspect=stage.clientWidth/stage.clientHeight;camera.updateProjectionMatrix();};const observer=new ResizeObserver(resize);observer.observe(stage);resize();
 disposeViewer=()=>{cancelAnimationFrame(frame);observer.disconnect();controls.dispose();scene.traverse(o=>{if(o instanceof THREE.Mesh){o.geometry.dispose();for(const m of Array.isArray(o.material)?o.material:[o.material]){for(const value of Object.values(m))if(value instanceof THREE.Texture)value.dispose();m.dispose();}}});renderer.dispose();renderer.forceContextLoss();};
 const gltf=await new GLTFLoader().loadAsync(asset.url);if(closed){gltf.scene.traverse(o=>{if(o instanceof THREE.Mesh){o.geometry.dispose();for(const m of Array.isArray(o.material)?o.material:[o.material])m.dispose();}});return;}
 model=gltf.scene;const box=new THREE.Box3().setFromObject(model),size=box.getSize(new THREE.Vector3()),center=box.getCenter(new THREE.Vector3()),scale=2/Math.max(size.x,size.y,size.z);model.scale.setScalar(scale);model.position.copy(center.multiplyScalar(-scale));scene.add(model);camera.position.set(2,1.1,2.5);controls.target.set(0,0,0);controls.update();stage.querySelector('p')?.remove();
 const animate=()=>{if(closed)return;frame=requestAnimationFrame(animate);controls.update();renderer.render(scene,camera);};animate();
 }catch{dialog.querySelector('.model-stage')!.innerHTML='<p role="alert">Não foi possível exibir o modelo. O arquivo GLB continua disponível para download.</p>';}
}
async function boot(){const res=await fetch('/assets/magnific/expansion/catalog.json');if(!res.ok)throw new Error('Acervo indisponível');const library=await res.json() as Library;let selected='TODOS';
 root.innerHTML=`<header class="top"><a class="brand" href="/">WAR CATS <span>TÁTICA / ARTE / CAMPO</span></a><a class="back" href="/">VOLTAR AO JOGO ↗</a></header><main><section class="intro"><div><p class="eyebrow">ACERVO DE CAMPO / MAGNIFIC</p><h1>MATÉRIA<br>DE COMBATE.</h1><p>Modelos, acabamentos e sons criados para o WAR CATS. Explore as referências, inspecione os objetos e baixe os arquivos.</p></div><dl><div><dt>CRIAÇÕES</dt><dd>${library.generated}</dd></div><div><dt>CRÉDITOS UTILIZADOS</dt><dd>${library.spent.toLocaleString('pt-BR')}</dd></div><div><dt>SALDO RESTANTE</dt><dd>${library.remaining}</dd></div></dl></section><section><div class="tools"><nav class="filters" aria-label="Tipo de asset"></nav><label class="search"><span>BUSCAR</span><input type="search" placeholder="Arma, material ou som" aria-label="Buscar no acervo"></label></div><p class="result-count" role="status"></p><div class="asset-grid"></div></section><footer class="page-footer">ARQUIVOS LOCAIS · MODELOS 3D PARA INSPEÇÃO E PRODUÇÃO · ARTE CONCEITUAL NÃO REPRESENTA CAPTURA DO JOGO</footer></main>`;
 const categories=['TODOS',...new Set(library.assets.map(a=>a.category))],filters=root.querySelector('.filters')!,search=root.querySelector('input')!;
 const render=()=>{const query=search.value.trim().toLowerCase(),assets=library.assets.filter(a=>(selected==='TODOS'||a.category===selected)&&a.name.toLowerCase().includes(query));filters.innerHTML=categories.map(c=>`<button aria-pressed="${selected===c}" data-filter="${escape(c)}">${escape(c)}</button>`).join('');filters.querySelectorAll<HTMLButtonElement>('button').forEach(b=>b.onclick=()=>{selected=b.dataset.filter!;render();});root.querySelector('.result-count')!.textContent=`${assets.length} arquivos disponíveis`;
 const grid=root.querySelector('.asset-grid')!;grid.innerHTML=assets.map(a=>{const audio=/\.(mp3|wav|ogg)$/.test(a.url),model=a.url.endsWith('.glb');return`<article class="asset ${audio?'audio-asset':''}"><div class="asset-preview">${audio?`<div class="sound-symbol" aria-hidden="true">▂ ▅ ▃ ▇ ▄ ▆ ▂</div><audio controls preload="none" src="${a.url}" aria-label="Ouvir ${escape(a.name)}"></audio>`:model?`<button class="model-open" data-model="${a.url}" aria-label="Inspecionar ${escape(a.name)} em 3D">${a.preview?`<img loading="lazy" src="${a.preview}" alt="${escape(a.name)}">`:''}<span>INSPECIONAR 3D ↗</span></button>`:`<a href="${a.url}" target="_blank" rel="noopener"><img loading="lazy" src="${a.url}" alt="${escape(a.name)}"></a>`}</div><div class="asset-caption"><span>${escape(a.category)} · ${(a.bytes/1024).toFixed(0)} KB</span><h2>${escape(a.name)}</h2><div><a href="${a.url}" download>BAIXAR ↓</a>${a.source?`<a href="${a.source}" target="_blank" rel="noopener">MAGNIFIC ↗</a>`:''}</div></div></article>`;}).join('');grid.querySelectorAll<HTMLButtonElement>('[data-model]').forEach(b=>b.onclick=()=>{const a=library.assets.find(a=>a.url===b.dataset.model);if(a)void viewer(a);});};search.addEventListener('input',render);render();
 root.addEventListener('play',event=>{root.querySelectorAll('audio').forEach(a=>{if(a!==event.target)a.pause();});},true);
}
void boot().catch(()=>{root.querySelector('[role="status"]')!.textContent='Não foi possível carregar o acervo. Recarregue para tentar novamente.';});
